services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: aiprep
      POSTGRES_PASSWORD: aiprep
      POSTGRES_DB: aiprep
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: